import { useState } from "react";
import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import Navbar from "@/components/layout/navbar";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
    const [darkMode, setDarkMode] = useState(false);
    const [lang, setLang] = useState("kor");

    const toggleDarkMode = () => {
        setDarkMode(!darkMode);
    };

    const toggleLang = () => {
        setLang(lang === "kor" ? "eng" : "kor");
    };

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <Navbar
                    darkMode={darkMode}
                    toggleDarkMode={toggleDarkMode}
                    lang={lang}
                    toggleLang={toggleLang}
                />
            </main>
        </>
    );
}
