import { useState } from "react";
import Head from "next/head";
import Image from "next/image";

import styled from "styled-components";

import Navbar from "@/components/layout/navbar";
import Introduce from "@/components/common/introduce";
import Skill from "@/components/common/skill";
import Footer from "@/components/layout/footer";

import ImgCard from "@/components/common/img-card";
import Project from "@/components/common/project";

export default function Home() {
    const [darkMode, setDarkMode] = useState(false);
    const [lang, setLang] = useState("kor");

    const Main = styled.main`
        background-color: #f9f9f9;
        padding: 10px 100px;
    `;

    const toggleDarkMode = () => {
        setDarkMode(!darkMode);
    };

    const toggleLang = () => {
        setLang(lang === "kor" ? "eng" : "kor");
    };

    return (
        <>
            <Head>
                <title>개발자 전진우 포트폴리오</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar
                darkMode={darkMode}
                toggleDarkMode={toggleDarkMode}
                lang={lang}
                toggleLang={toggleLang}
            />
            <Main>
                <Introduce />
                <Skill />
                <Project />
            </Main>
            <Footer />
        </>
    );
}
